---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-deployment
  namespace: uyuni
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uyuni
  template:
    metadata:
      labels:
        app: uyuni
    spec:
      containers:
        - name: uyuni
          image: localhost/uyuni
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "2048Mi"
              cpu: "300m"
          ports:
          - containerPort: 443
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: uyuni-service
  namespace: uyuni
spec:
  ports:
  - protocol: "TCP"
    port: 443
    targetPort: 443

  selector:
    app: uyuni
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: uyuni-ingress
  namespace: uyuni
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /rhn/*
        backend:
          serviceName: uyuni-service
          servicePort: 443
